sudo: required
language: python

services:
  - docker

env:
  matrix:
    - PGTAG=9.6
    - PGTAG=9.5
    - PGTAG=9.4

python:
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install codecov

script: python -m pytest --verbose --cov=pg_bawler --cov-report=term-missing tests

after_success:
  - codecov
