version: '2'

services:
  pg_bawler:
    build: .
    volumes:
      - /usr/local/lib/
      - .:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: pg_bawler-test-pg
