version: '2'

services:

  pg_bawler:
    build: .
    command: /bin/sh live_runtests.sh
    volumes:
      - /usr/local/lib/
      - .:/code
    depends_on:
      - postgres
    container_name: pg_bawler-test-lib

  postgres:
    image: postgres:latest
    container_name: pg_bawler-test-pg
