version: '2'

services:

  postgres:
    image: postgres:latest
    container_name: pg_bawler-test-pg
    environment: &pg_environment
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: bawler_test
      POSTGRES_DB: bawler_test

  pg_bawler:
    build: .
    command: watchmedo tricks-from watchmedo-tricks.yaml
    volumes:
      - .:/opt/pg_bawler
    depends_on:
      - postgres
    container_name: pg_bawler-test-lib
    environment:
      <<: *pg_environment
      PYTHONASYNCIODEBUG: 1
